from _typeshed import Incomplete as Incomplete

class Proxy:
    def __init__(self, ip: Union[Incomplete, None] = ..., port: Union[Incomplete, None] = ..., username: Union[Incomplete, None] = ..., password: Union[Incomplete, None] = ...) -> None: ...
    @property
    def ip(self) -> None: ...
    @property
    def port(self) -> None: ...
    @property
    def username(self) -> None: ...
    @property
    def password(self) -> None: ...
    @property
    def http(self) -> None: ...
    @property
    def https(self) -> None: ...
    @property
    def telegram_http(self) -> None: ...
    @property
    def telegram_socks5(self) -> None: ...
    @property
    def telegram_socks4(self) -> None: ...
    @property
    def socks5(self) -> None: ...
    @property
    def socks4(self) -> None: ...
