from _typeshed import Incomplete

class Proxy:
    def __init__(self, ip: Incomplete | None = ..., port: Incomplete | None = ..., username: Incomplete | None = ..., password: Incomplete | None = ...) -> None: ...
    @property
    def ip(self): ...
    @property
    def port(self): ...
    @property
    def username(self): ...
    @property
    def password(self): ...
    @property
    def http(self): ...
    @property
    def https(self): ...
    @property
    def telegram_http(self): ...
    @property
    def telegram_socks5(self): ...
    @property
    def telegram_socks4(self): ...
    @property
    def socks5(self): ...
    @property
    def socks4(self): ...
