from ._types import ProxiesList as ProxiesList, ProxyiesGen as ProxyiesGen
from .logger import console_handler as console_handler, file_handler as file_handler, logger as logger
from .proxy import Proxy as Proxy
from typing import Any, Dict, List, Optional

class ProxiesReader:
    def __init__(self, file_path: str = ..., shuffle: bool = ..., debug: bool = ..., extra_debug: bool = ...) -> None: ...
    @property
    def total(self) -> int: ...
    @property
    def total_working(self) -> int: ...
    @property
    def total_bad(self) -> int: ...
    @property
    def proxies(self) -> ProxiesList: ...
    @property
    def bad_proxies(self) -> ProxiesList: ...
    @property
    def working_proxies(self) -> ProxiesList: ...
    def read_raw(self) -> List[str]: ...
    def read_with_auth(self) -> None: ...
    def read_authless(self) -> None: ...
    async def check_all_proxies(self, max_resp_time: int = ...) -> None: ...
    async def check_all_proxies_socks5(self, max_resp_time: int = ...) -> None: ...
    def get_working_proxies_list_http(self) -> List[str]: ...
    def write_working_proxies(self, filename: str) -> None: ...
    def get_random_http(self) -> Optional[str]: ...
    def get_random_socks5(self) -> Optional[str]: ...
    def get_random_socks5_telegram(self) -> Optional[Dict[str, Any]]: ...
    def next_http_from_list(self) -> Optional[str]: ...
    def next_http_from_cycle(self) -> str: ...
    def next_socks5_from_list(self) -> str: ...
    def next_socks5_from_cycle(self) -> str: ...
    def next_http_telegram_from_list(self) -> Dict[str, Any]: ...
    def next_http_telegram_from_cycle(self) -> Dict[str, Any]: ...
    def next_socks5_telegram_from_cycle(self) -> Dict[str, Any]: ...
    def next_socks5_telegram_from_list(self) -> Dict[str, Any]: ...
    def next_https_from_list(self) -> str: ...
    def next_https_from_cycle(self) -> str: ...
